version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: estudoar-ts-api
    command: npm run debug
    volumes:
      - ./dist:/usr/src/estudoar-ts-api/dist
      - ./package.json:/usr/src/estudoar-ts-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo